### ISSUE TITLE
CipherHelper.transform unclear

### ISSUE THREAD

**Issue by diamondo25** [Yaminike/MapleScala#1]
I've looked into how it actually worked, and I suggest you add/change the transform function to be more clear:

https://github.com/diamondo25/Maple.js/blob/master/net/socket.js#L178

**Comment by Yaminike** [comment]
Personally I do not think it is possible to be more clear, mainly due the fact I store the IV as an Int, rather than an byte array.
This because the shuffle functions works with Int, rather than bytes.
So changing anything would either hurt performance, or require me to rewrite most of the class.
Which is to much work for a rather insignificant change. (as it not being 'clear' is discuss-able, as it makes enough sense for me)

I guess I will have to add some comments later on, this so the bitwise operators will be easier to understand.
Thank you.
